#!/usr/bin/env python3
"""
TGR Mega Archive - Consolidates old posts per celebrity into rich summary posts.

For each celebrity with posts older than ARCHIVE_DAYS:
  - Groups posts by celebrity
  - Creates one "mega post" summarising all stories
  - Writes 301 redirects from each old post slug to the mega post
  - Moves old posts to _archive/

This keeps the site fast (fewer active posts), preserves SEO (no 404s),
and creates richer content (one well-linked page per celebrity arc).

Usage:
  python3 scripts/mega_archive.py --dry-run    # preview
  python3 scripts/mega_archive.py              # run
  python3 scripts/mega_archive.py --days 14   # custom threshold
"""

import re
import yaml
import json
import shutil
import argparse
from pathlib import Path
from datetime import datetime, timedelta
from collections import defaultdict

SITE_BASE = "https://thegossroom.com"

class MegaArchiver:
    def __init__(self, dry_run=False, archive_days=30, min_posts=3):
        self.dry    = dry_run
        self.days   = archive_days
        self.min    = min_posts          # min posts before consolidating
        self.base   = Path(".")
        self.posts  = self.base / "_posts"
        self.archive= self.base / "_archive"
        self.data   = self.base / "_data"
        self.archive.mkdir(exist_ok=True)

        # Load existing redirects
        self.redirects_file = self.base / "_redirects"
        self.redirects = self._load_redirects()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _load_redirects(self):
        if self.redirects_file.exists():
            lines = self.redirects_file.read_text().splitlines()
            return [l for l in lines if l.strip() and not l.startswith("#")]
        return []

    def _save_redirects(self):
        header = "# Auto-generated by mega_archive.py\n# DO NOT EDIT MANUALLY\n"
        content = header + "\n".join(sorted(set(self.redirects))) + "\n"
        if not self.dry:
            self.redirects_file.write_text(content)
        print(f"  Redirects: {len(self.redirects)} rules")

    def _post_url(self, filename):
        stem = filename.replace(".md", "")
        if len(stem) < 11:
            return None
        try:
            y, m, d = stem[:10].split("-")
            slug = re.sub(r"-+", "-", stem[11:]).strip("-")
            return f"{SITE_BASE}/{y}/{m}/{d}/{slug}/"
        except Exception:
            return None

    def _parse(self, path):
        try:
            content = path.read_text(encoding="utf-8")
            if not content.startswith("---"):
                return None, None
            parts = content.split("---", 2)
            if len(parts) < 3:
                return None, None
            fm = yaml.safe_load(parts[1]) or {}
            return fm, parts[2].strip()
        except Exception:
            return None, None

    def _date_from_file(self, path):
        try:
            return datetime.strptime(path.name[:10], "%Y-%m-%d")
        except Exception:
            return datetime.now()

    # ------------------------------------------------------------------
    # Main logic
    # ------------------------------------------------------------------

    def find_archivable_posts(self):
        """Find posts older than threshold, grouped by primary celebrity."""
        cutoff = datetime.now() - timedelta(days=self.days)
        groups = defaultdict(list)

        for f in self.posts.glob("*.md"):
            date = self._date_from_file(f)
            if date >= cutoff:
                continue  # Too recent

            fm, body = self._parse(f)
            if not fm:
                continue

            celeb = fm.get("primary_celebrity", "").strip()
            if not celeb:
                celeb = "_uncategorised"

            groups[celeb].append({
                "file": f,
                "fm": fm,
                "body": body,
                "date": date,
                "url": self._post_url(f.name),
            })

        # Only consolidate celebrities with enough old posts
        return {k: v for k, v in groups.items() if len(v) >= self.min}

    def create_mega_post(self, celebrity, posts):
        """Create one rich summary post for a celebrity's old stories."""
        posts_sorted = sorted(posts, key=lambda x: x["date"], reverse=True)
        newest = posts_sorted[0]["date"]
        oldest = posts_sorted[-1]["date"]

        celeb_display = celebrity.replace("_", " ").title()
        date_str = datetime.now().strftime("%Y-%m-%d")
        slug = f"{celebrity}-archive"
        filename = f"{date_str}-{slug}.md"
        mega_url = self._post_url(filename)

        # Build rich body
        sections = []
        for p in posts_sorted:
            title = p["fm"].get("title", "Untitled")
            src_url = p["fm"].get("source_url", "")
            src = p["fm"].get("source", "")
            date_fmt = p["date"].strftime("%B %d, %Y")
            body_excerpt = (p["body"] or "")[:300].strip()
            if len(p["body"] or "") > 300:
                body_excerpt += "..."

            section = f"### {title}\n"
            section += f"*{date_fmt}*"
            if src:
                section += f" — [{src}]({src_url})" if src_url else f" — {src}"
            section += f"\n\n{body_excerpt}\n"
            sections.append(section)

        # Aggregate scores
        avg_temp = sum(p["fm"].get("temperature", 0) for p in posts) / len(posts)
        max_drama = max(p["fm"].get("drama_score", 0) for p in posts)
        all_tags = list({t for p in posts for t in p["fm"].get("tags", [])})

        fm_out = {
            "layout": "post",
            "title": f"{celeb_display}: Complete Story Archive",
            "slug": slug,
            "date": datetime.now().isoformat(),
            "primary_celebrity": celebrity,
            "is_mega_archive": True,
            "story_count": len(posts),
            "date_range_start": oldest.strftime("%Y-%m-%d"),
            "date_range_end": newest.strftime("%Y-%m-%d"),
            "temperature": round(avg_temp),
            "drama_score": max_drama,
            "tags": all_tags[:10],
            "categories": ["archive", "gossip"],
            "description": (
                f"Complete archive of {len(posts)} stories about {celeb_display} "
                f"from {oldest.strftime('%B %Y')} to {newest.strftime('%B %Y')}."
            ),
        }

        body_out = f"""## {celeb_display} — {len(posts)} Stories

*Covering {oldest.strftime('%B %Y')} through {newest.strftime('%B %Y')}*

This archive consolidates all stories about {celeb_display} into one navigable page.

---

""" + "\n\n---\n\n".join(sections)

        content = f"---\n{yaml.dump(fm_out, default_flow_style=False)}---\n\n{body_out}\n"
        return filename, content, mega_url

    def run(self):
        print(f"🗂️  Mega Archive {'(DRY RUN)' if self.dry else ''}")
        print(f"   Threshold: {self.days} days, min {self.min} posts to consolidate")

        groups = self.find_archivable_posts()

        if not groups:
            print("   Nothing to consolidate.")
            return

        total_old = sum(len(v) for v in groups.values())
        print(f"   Found {len(groups)} celebrities, {total_old} posts to consolidate\n")

        created = 0
        archived = 0
        redirected = 0

        for celeb, posts in sorted(groups.items()):
            print(f"  📦 {celeb.replace('_',' ').title()} — {len(posts)} posts")

            filename, content, mega_url = self.create_mega_post(celeb, posts)

            # Write mega post
            mega_path = self.posts / filename
            if not self.dry:
                mega_path.write_text(content, encoding="utf-8")
            print(f"     → Mega post: {filename}")
            created += 1

            # Archive old posts + write redirects
            for p in posts:
                old_url = p["url"]
                if old_url and mega_url:
                    redirect_line = f"{old_url.replace(SITE_BASE, '')} {mega_url.replace(SITE_BASE, '')} 301"
                    self.redirects.append(redirect_line)
                    redirected += 1

                archive_path = self.archive / p["file"].name
                if not self.dry:
                    shutil.move(str(p["file"]), str(archive_path))
                archived += 1

        self._save_redirects()

        print(f"\n✅ Done:")
        print(f"   {created} mega posts created")
        print(f"   {archived} old posts archived")
        print(f"   {redirected} redirects written to _redirects")
        if not self.dry:
            print(f"\n   Commit _redirects and _posts/ then push.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--days", type=int, default=30)
    parser.add_argument("--min-posts", type=int, default=3)
    args = parser.parse_args()
    MegaArchiver(dry_run=args.dry_run, archive_days=args.days, min_posts=args.min_posts).run()
