name: Emergency YAML Fix v2
on:
  workflow_dispatch:

jobs:
  fix-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create backup branch
        run: |
          git checkout -b backup-yaml-v2-$(date +%Y%m%d-%H%M%S)
          git push origin backup-yaml-v2-$(date +%Y%m%d-%H%M%S)
          git checkout main

      - name: Run YAML fix v2
        run: python scripts/fix_yaml.py

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔧 Fix quoted YAML tags in Jekyll posts"
          file_pattern: "_posts/*.md"
