name: Emergency YAML Fix
on:
  workflow_dispatch:

jobs:
  fix-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create backup branch
        run: |
          git checkout -b backup-yaml-$(date +%Y%m%d-%H%M%S)
          git push origin backup-yaml-$(date +%Y%m%d-%H%M%S)
          git checkout main

      - name: Run YAML fix
        run: python scripts/fix_yaml.py

      - name: Show summary
        run: cat yaml_fix_summary.txt

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚨 Emergency fix: Restore proper YAML syntax"
          file_pattern: "_posts/*.md yaml_fix_summary.txt"
