name: Update Celebrity Database

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-celebrities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Update celebrities.yml
      run: |
        python -c "
        import yaml
        import os
        from collections import OrderedDict

        # Load existing celebrities
        with open('_data/celebrities.yml', 'r') as f:
            celebrities = yaml.safe_load(f) or {}

        print(f'Loaded {len(celebrities)} existing celebrities')

        # Missing celebrities to add
        missing_celebrities = {
            'sydney_sweeney': {'category': 'actor', 'drama_score': 85},
            'liam_neeson': {'category': 'actor', 'drama_score': 70},
            'natasha_richardson': {'category': 'actor', 'drama_score': 65},
            'travis_kelce': {'category': 'athlete', 'drama_score': 80},
            'jason_kelce': {'category': 'athlete', 'drama_score': 70},
            'ed_kelce': {'category': 'celebrity_family', 'drama_score': 60},
            'anne_hathaway': {'category': 'actor', 'drama_score': 65},
            'matt_rife': {'category': 'comedian', 'drama_score': 70},
            'stephen_colbert': {'category': 'tv_host', 'drama_score': 60},
            'rod_stewart': {'category': 'musician', 'drama_score': 65},
            'ozzy_osbourne': {'category': 'musician', 'drama_score': 75},
            'harrison_ford': {'category': 'actor', 'drama_score': 70},
            'machine_gun_kelly': {'category': 'musician', 'drama_score': 65},
            'mgk': {'category': 'musician', 'drama_score': 65},
            'sarah_michelle_gellar': {'category': 'actor', 'drama_score': 60},
            'martha_stewart': {'category': 'entrepreneur', 'drama_score': 70},
            'loni_anderson': {'category': 'actor', 'drama_score': 55},
            'alix_earle': {'category': 'influencer', 'drama_score': 70},
            'alex_cooper': {'category': 'podcaster', 'drama_score': 65},
            'whitney_port': {'category': 'reality_tv', 'drama_score': 50},
            'colton_underwood': {'category': 'reality_tv', 'drama_score': 55},
            'cynthia_nixon': {'category': 'actor', 'drama_score': 55},
            'kristin_davis': {'category': 'actor', 'drama_score': 55},
            'brooke_hogan': {'category': 'reality_tv', 'drama_score': 50},
            'hulk_hogan': {'category': 'wrestler', 'drama_score': 70},
            'erik_menendez': {'category': 'criminal', 'drama_score': 75},
            'lyle_menendez': {'category': 'criminal', 'drama_score': 75},
            'nikki_garcia': {'category': 'wrestler', 'drama_score': 60},
            'brie_garcia': {'category': 'wrestler', 'drama_score': 60},
            'ghislaine_maxwell': {'category': 'criminal', 'drama_score': 80},
            'elizabeth_holmes': {'category': 'entrepreneur', 'drama_score': 75},
            'jen_shah': {'category': 'reality_tv', 'drama_score': 65},
            'kate_gosselin': {'category': 'reality_tv', 'drama_score': 55},
            'christina_haack': {'category': 'tv_host', 'drama_score': 55},
            'heather_rae_el_moussa': {'category': 'reality_tv', 'drama_score': 50},
            'tarek_el_moussa': {'category': 'tv_host', 'drama_score': 50},
            'kelly_dodd': {'category': 'reality_tv', 'drama_score': 60},
            'bryan_kohberger': {'category': 'criminal', 'drama_score': 70},
            'mandy_moore': {'category': 'actor', 'drama_score': 60},
            'caitlin_clark': {'category': 'athlete', 'drama_score': 70},
            'breanna_stewart': {'category': 'athlete', 'drama_score': 60},
            'pamela_anderson': {'category': 'actor', 'drama_score': 70},
            'michelle_yeoh': {'category': 'actor', 'drama_score': 65},
            'anna_kendrick': {'category': 'actor', 'drama_score': 65},
            'dakota_johnson': {'category': 'actor', 'drama_score': 65},
            'jennifer_garner': {'category': 'actor', 'drama_score': 65},
            'tom_cruise': {'category': 'actor', 'drama_score': 80},
            'ana_de_armas': {'category': 'actor', 'drama_score': 70},
            'anna_camp': {'category': 'actor', 'drama_score': 50},
            'sha_carri_richardson': {'category': 'athlete', 'drama_score': 65},
            'shacarri_richardson': {'category': 'athlete', 'drama_score': 65},
            'olympian_sha_carri_richardson': {'category': 'athlete', 'drama_score': 65}
        }

        # Add missing celebrities with their variations
        added_count = 0
        for name, info in missing_celebrities.items():
            if name not in celebrities:
                celebrities[name] = info
                added_count += 1
                print(f'Added: {name}')

        # Add common variations and nicknames
        variations = {
            'kelce': {'category': 'athlete', 'drama_score': 75},
            'menendez': {'category': 'criminal', 'drama_score': 75},
            'garcia_twins': {'category': 'wrestler', 'drama_score': 60},
            'bella_twins': {'category': 'wrestler', 'drama_score': 60},
            'el_moussa': {'category': 'tv_host', 'drama_score': 50},
            'hogan': {'category': 'wrestler', 'drama_score': 70},
            'richardson': {'category': 'athlete', 'drama_score': 65},
        }

        for name, info in variations.items():
            if name not in celebrities:
                celebrities[name] = info
                added_count += 1
                print(f'Added variation: {name}')

        # Sort celebrities alphabetically
        sorted_celebrities = OrderedDict(sorted(celebrities.items()))

        # Write back to file with proper formatting
        with open('_data/celebrities.yml', 'w') as f:
            yaml.dump(dict(sorted_celebrities), f, default_flow_style=False, sort_keys=False, allow_unicode=True)

        print(f'Added {added_count} new celebrities')
        print(f'Total celebrities: {len(sorted_celebrities)}')
        "

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/celebrities.yml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Add missing celebrities to database"
          git push
        fi
